apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-deployer
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  containers:
    - name: trivy
      image: aquasec/trivy:0.58.1
      command: ["cat"]
      tty: true
      env:
        - {name: TRIVY_CACHE_DIR, value: /trivy-cache}
      volumeMounts: [{name: trivy-cache, mountPath: /trivy-cache}]
      resources: {requests: {cpu: 200m, memory: 512Mi}, limits: {memory: 2Gi}}
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      command: ["/busybox/cat"]
      tty: true
      resources: {requests: {cpu: 500m, memory: 512Mi}, limits: {memory: 2Gi}}
    - name: crane
      image: gcr.io/go-containerregistry/crane:debug
      command: ["/busybox/cat"]
      tty: true
    - name: tools
      image: curlimages/curl:8.11.1
      command: ["cat"]
      tty: true
      securityContext: {runAsUser: 1000}
  volumes:
    - name: trivy-cache
      emptyDir: {}
